version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./project:/var/www/html/project
    depends_on:
      - php
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        UID: $UID
        GID: $GID
        UNAME: $UNAME
    volumes:
      - ./project:/var/www/html/project
    env_file:
      - ./.env
    tty: true
    depends_on:
      - mysql
  node:
    image: node:lts
    tty: true
    volumes:
      - ./project:/var/www/html/project
    working_dir: /var/www/html/project
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
